Kino-68
DrBackmischung/Kino-Backend pull request #11
Opened 2021-12-05 17:27 UTC by DrBackmischung

## Pull Request
Ticket: https://dhbw-ma-wwi2020seb.atlassian.net/browse/KINO-XX

### Neue Features:

- [ ] Tests für Controller

### Beschreibung:

### Check:

* [ ] Funktionieren die Tests?
* [ ] Code Coverage eingehalten?
* [ ] Dokumentation?

2021-12-06 15:33 UTC, Tsawlen requested changes
Kein setId() => Das böse (ich hoffe es geht mit MockBean XD)

===== [ Request Changes ] =====

2021-12-06 15:33 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/Cinema.java
> +	public void setId(UUID id) {
AUA, AUA, AUA.
Bitte benutz MockBean, dann wird auch automatisch eine ID gesetzt.
AUA, AUA, AUA

(setID ist bei generierten UUIDs sehr ungünstig, das sollten wir nicht drin haben, kann Konflikte geben, also bitte weg damit)

2021-12-06 15:33 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/CinemaRoom.java
> +	public void setId(UUID id) {
Diese schmerzen

2021-12-06 15:33 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/CinemaRoomSeatingPlan.java
> +	public void setId(UUID id) {
es brennt

2021-12-06 15:33 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/City.java
> +	public void setId(UUID id) {
DIESE SCHMERZEN

2021-12-06 15:33 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/Movie.java
> +	public void setId(UUID id) {
Ich sterbe!

2021-12-06 15:33 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/Seat.java
> +	public void setId(UUID id) {
Ruft einen Krankenwagen

2021-12-06 15:33 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/Show.java
> +	public void setId(UUID id) {
Aber nicht für mich!

2021-12-06 15:33 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/Ticket.java
> +	public void setId(UUID id) {
DAM DAM DAAAAAAA

2021-12-06 15:33 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/User.java
> +	public void setId(UUID id) {
Okay, doch für mich :c

2021-12-06 21:19 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/entities/Cinema.java
> +	public void setId(UUID id) {
Wird es leider nicht :(

2021-12-06 22:01 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaController.java
> +		return new ResponseEntity<>(cinemaRepository.findAll(),HttpStatus.OK);
Wenn ich nach "isOk()" frage im Test wird ja nach 200 geprüft, das bekomme ich mit HttpStatus.OK. Das FOUND sorgt dafür, dass ich nur eine Weiterleitung erhalte.

2021-12-06 22:09 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaController.java
> +			return new ResponseEntity<>(id, HttpStatus.NO_CONTENT);
Denkst du das kann ich so ändern? Weil 200 scheint ja nicht unbedingt passend für ein "Hier existiert das Objekt nicht mehr" @Tsawlen

2021-12-07 20:56 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaController.java
> +			return new ResponseEntity<>(id, HttpStatus.NO_CONTENT);
Halte ich für unpassend. Weil Anfrage lösche XY, wurde gelöscht => „OK“
Anfrage lösche XY, XY nicht gefunden => „NOT_FOUND“
Also m.M.n.

2021-12-07 20:57 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaController.java
> +		return new ResponseEntity<>(cinemaRepository.findAll(),HttpStatus.OK);
Ist okay

2021-12-07 21:30 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaController.java
> +			return new ResponseEntity<>(id, HttpStatus.NO_CONTENT);
Wenn ich XY halt suche nach dem Löschen bekomme ich ein OK

2021-12-18 15:29 UTC, Tsawlen approved these changes
Nur eine Stelle solltest du nochmal überprüfen, aber erstmal okay.
Kino-68 sieht nach verdammt viel und nerviger Arbeit aus.

LGTM

2021-12-18 15:29 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CityController.java
> +	@DeleteMapping("/{id}")
Wird so nicht funktionieren.
Muss wegen Children die Annotation "@Transactional" haben. 
Zudem sollte geprüft werden ob mit Ausführung des Calls auch die verknüpften Kinos gelöscht werden

2021-12-18 19:39 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CityController.java
> +	@DeleteMapping("/{id}")
@Transactional hinzugefügt

2021-12-18 19:40 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CityController.java
> +	@DeleteMapping("/{id}")
Die fancy tests würde ich an anderer Stelle noch machen - da kommen noch paar auf uns zu, die nicht zwingend zu den Grundlagen gehören

2021-12-18 19:41 UTC, merged