Kino-123
DrBackmischung/Kino-Backend pull request #16
Opened 2021-12-09 19:44 UTC by Tsawlen

+ CinemaRoomController
   + addCinemaRoom
   + updateCinemaRoom
   + getAll
   + getSpecific
   + deleteCinemaRoom
+ CinemaRoomConfigurationObject

## Pull Request
Ticket: https://dhbw-ma-wwi2020seb.atlassian.net/browse/KINO-123

### Neue Features:

- [x] Add a new CinemaRoom
- [x] Add a cinema to CinemaRoom by UUID
- [x] CinemaRoomConfigurationObject

### Beschreibung:
Mit diesem Update ist der Controller für einen Kinosaal hinzugefügt, welcher per Konfigurationsobjekt erstellt werden kann, also mit allen Parametern wie der Kinosaal selber, allerdings die Fremdschlüssel als UUID statt des gesamten Objektes, da dies eine bessere Performance bewirkt. 

### Check:

* [x] Funktionieren die Tests?
* [ ] Code Coverage eingehalten?
* [ ] Dokumentation?

2021-12-09 20:17 UTC, DrBackmischung requested changes

2021-12-09 20:17 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/communicationObjects/CinemaRoomCommunicationObject.java
> +public class CinemaRoomCommunicationObject {
Communication?

2021-12-09 20:17 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaRoomController.java
> +	@PutMapping
zB im Cinema hast du /add benutzt, wollen wir das konstistent halten?

2021-12-09 20:45 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaRoomController.java
> +	@PutMapping
Jap, dann entferne ich überall anders das „/add“

2021-12-09 20:48 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/communicationObjects/CinemaRoomCommunicationObject.java
> +public class CinemaRoomCommunicationObject {
Ein Objekt, welches nur der Kommunikation und Erstellung von CinemaRoom Objekten dient. 
Wird also nie für einen anderen Zweck verwendet als von Frontend erstellt, vom backend verwendet und danach gelöscht zu werden. 
Brauche ich, sonst kann ich nur Objekte mit den Referenzobjekten im Bauch erstellen, was natürlich blöd wäre.

2021-12-09 22:14 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/communicationObjects/CinemaRoomCommunicationObject.java
> +public class CinemaRoomCommunicationObject {
Dachte nur, dass das Configuration heißen sollte - aber mein gehirn ist einfach nur verwirrt generell :D

2021-12-09 22:15 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CinemaRoomController.java
> +	@PutMapping
ich finde das /add aber schön :(
So kennt man das auch von anderen Webseiten etc.

2021-12-11 16:05 UTC, DrBackmischung approved these changes
Code LGTM! (das /add ist toll hehe)

2021-12-11 16:12 UTC, merged