Kino-70
DrBackmischung/Kino-Backend pull request #30
Opened 2021-12-23 20:27 UTC by DrBackmischung

## Pull Request
Ticket: https://dhbw-ma-wwi2020seb.atlassian.net/browse/KINO-70

### Neue Features:

- [ ] Registrierung
- [ ] Login
- [ ] Mail Configuration
- [ ] Confirmation Mail
- [ ] Forget Password
- [ ] Profile 
- [ ] Tickets/Reviews/News for logged in user

### Beschreibung:

User Management with multiple calls
[ ] /registration
[ ] /login
[ ] /forget/id
[ ] /confirm/id
[ ] /reset/id
[ ] /user/id/tickets
[ ] /user/id/reviews
[ ] /creditcard
[ ] /paypal 

### Check:

* [ ] PR geht gegen DEV und nicht MAIN!
* [ ] Funktionieren die Tests?
* [ ] Code Coverage eingehalten?
* [ ] Dokumentation?

2022-01-03 11:47 UTC, Tsawlen requested changes
Funktioniert, hat aber noch schwächen

2022-01-03 11:47 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/configurationObject/UserConfigurationObject.java
> +	public UUID cityID;
Würde hier eher auch String city, int plz verwenden, weil die Stadt eventuell noch nicht existiert und erst erstellt werden muss.

2022-01-03 11:47 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/configurationObject/UserRegistrationObject.java
> +	public UUID cityID;
Würde hier eher auch String city, int plz verwenden, weil die Stadt eventuell noch nicht existiert und erst erstellt werden muss.

2022-01-03 11:47 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/RegistrationController.java
> +@RestController
@RequestMapping("/registration")

2022-01-03 11:47 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/RegistrationController.java
> +	@PutMapping("/registration")
mapping ("/add")

2022-01-03 11:47 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/RegistrationController.java
> +	@PutMapping("/login")
Was macht das im Registration Controller?

2022-01-03 11:47 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/RegistrationController.java
> +			Optional<City> citySearch = cityRepository.findById(uro.cityID);
Würde es anders machen:
Suchen ob Stadt existiert (cityRepository.findByPlz(int plz);)
=> Wenn ja, City setzen
=> Wenn nein, City erstellen

2022-01-03 11:47 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/services/UserService.java
> +
Methoden:
addCreditCard
addPayPal
auch im entsprechenden Controller

2022-01-04 10:27 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/RegistrationController.java
> +@RestController
ne

2022-01-04 10:27 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/RegistrationController.java
> +	@PutMapping("/registration")
wäre redundant, /registration/add benutzt niemand, man kennt registration eifach so

2022-01-04 10:28 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/RegistrationController.java
> +	@PutMapping("/login")
Weil ich nen Controller für Login/Registration bauen wollte, ich kann den umbenennen den Controller - aber ich will nicht für jeden eigenen Aufruf nen eigenen Controller

2022-01-04 10:28 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/services/UserService.java
> +
dafür gibt es dann update vom User

2022-01-04 20:01 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/RegistrationController.java
> +			Optional<City> citySearch = cityRepository.findById(uro.cityID);
Der übergibt ja gar keine PLZ, ich bau das noch um

2022-01-06 07:55 UTC, Tsawlen reviewed
Paar Anmerkungen. 
höre langsam auf den Code Lesens zu können - Augen wurden getropft. Aber sieht soweit wie ich es sehen kann gut aus. 
Nur noch die Anmerkungen, dann approve

2022-01-06 07:55 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/TokenController.java
> +	TokenRepository repo;
Name zu generic m.M.n.
Eher tokenRepo ?

2022-01-06 07:55 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/UserController.java
> +				Optional<CreditCard> creditCardSearch = creditCardRepository.findById(uco.creditCardID);
Vielleicht eine create für die creditcard

2022-01-06 07:55 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/services/SeatService.java
> +			SemaphoreVault.getSemaphore(showId).acquire();
Ist das getestet, dass das funktioniert?

2022-01-06 07:55 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/services/SeatService.java
> +			SemaphoreVault.getSemaphore(showId).release();
Getestet?

2022-01-06 07:55 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/services/SeatService.java
> +			SemaphoreVault.getSemaphore(showId).release();
Getestet?

2022-01-07 10:41 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/UserController.java
> +				Optional<CreditCard> creditCardSearch = creditCardRepository.findById(uco.creditCardID);
gemacht

2022-01-07 17:22 UTC, Tsawlen approved these changes
Nur eine Anmerkung, aber nichts was geändert werden muss, also
LGTM

2022-01-07 17:22 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/CreditCardController.java
> +	@GetMapping("/getAll")
Würd ich nicht einbauen - Würde nicht die Möglichkeit geben alle Kreditkarteninformationen abzurufen

2022-01-07 22:13 UTC, merged