Kino-193
DrBackmischung/Kino-Backend pull request #41
Opened 2022-01-05 21:55 UTC by DrBackmischung

## Pull Request
Ticket: https://dhbw-ma-wwi2020seb.atlassian.net/browse/KINO-XX

### Neue Features:

- [ ] Calls für Profil vom User

### Beschreibung:

Tickets, Bookings, News und Reviews userspezifisch zurückgeben

### Check:

* [ ] PR geht gegen DEV und nicht MAIN!
* [ ] Funktionieren die Tests?
* [ ] Code Coverage eingehalten?
* [ ] Dokumentation?

2022-01-06 07:44 UTC, Tsawlen requested changes
Warum alles Downloaden und dann suchen, wenn JPA schon mit der Einschränkung suchen kann?

2022-01-06 07:44 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/ProfileController.java
> +		Iterable<Ticket> list = ticketRepository.findAll();
Das ist doch ein Job für JPA?

2022-01-06 07:44 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/ProfileController.java
> +		Iterable<Ticket> list = ticketRepository.findAll();
Das ist doch auch ein Job fürs JPA

2022-01-06 07:44 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/ProfileController.java
> +		Iterable<Review> list = reviewRepository.findAll();
Ebenfalls ein Job für JPA

2022-01-06 07:44 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/ProfileController.java
> +		Iterable<News> list = newsRepository.findAll();
Auch ein Job fürs JPA

2022-01-07 10:13 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/ProfileController.java
> +		Iterable<Ticket> list = ticketRepository.findAll();
Bookings hat kein User

2022-01-07 10:16 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/ProfileController.java
> +		Iterable<Ticket> list = ticketRepository.findAll();
Dann habe ich da scheiße gebaut. Da gehört selbstverständlich ein User rein

2022-01-07 17:18 UTC, Tsawlen reviewed
Soweit approved

2022-01-07 17:19 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/controller/ProfileController.java
> +		Iterable<Ticket> list = ticketRepository.findAll();
Ist jetzt im dev da => Eventuell umstellen?

2022-01-07 21:43 UTC, Tsawlen approved these changes
Code LGTM

2022-01-07 22:14 UTC, merged