Kino-248
DrBackmischung/Kino-Backend pull request #49
Opened 2022-01-09 17:16 UTC by Tsawlen

## Pull Request
Ticket: https://dhbw-ma-wwi2020seb.atlassian.net/browse/KINO-248

### Neue Features:

- [x] Suche nur Shows von Abfragedatum bis nächsten Donnerstag

### Beschreibung:
Suche nur Shows von Abfragedatum bis nächsten Donnerstag

### Check:

* [x] PR geht gegen DEV und nicht MAIN!
* [ ] Funktionieren die Tests?
* [ ] Code Coverage eingehalten?
* [x] Dokumentation?

2022-01-09 17:21 UTC, DrBackmischung requested changes

2022-01-09 17:21 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/MovieController.java
> +	public ResponseEntity<Object> getShowsForMovieTest(@PathVariable UUID id){
Warum MovieTest?

2022-01-09 17:21 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/controller/MovieController.java
> +	/* DEPRICATED
Kann das nicht weg?

2022-01-09 18:04 UTC, DrBackmischung requested changes

2022-01-09 18:04 UTC, DrBackmischung commented on src/test/java/de/wi2020sebgroup1/cinema/controller/MovieControllerTest.java
> +        mvc.perform(get("/movie"))
jetzt schon? wollen wir das nicht gleichzeitig für alle machen wenn wir am ende sind und alle calls haben? Ich würde auch eher /movies sagen statt /movie, und bei ID zB ist /movies/id auch noch gut bzw richtig - zumindest bauen "normale" APIs das so immer auf

2022-01-09 18:05 UTC, Tsawlen commented on src/test/java/de/wi2020sebgroup1/cinema/controller/MovieControllerTest.java
> +        mvc.perform(get("/movie"))
Alles klar, können wir so machen. 
dann ändere ich das wieder zurück - nachher

2022-01-10 15:40 UTC, DrBackmischung approved these changes

2022-01-11 09:24 UTC, merged