Kino-266
DrBackmischung/Kino-Backend pull request #58
Opened 2022-01-16 00:06 UTC by Tsawlen

## Pull Request
Ticket: https://dhbw-ma-wwi2020seb.atlassian.net/browse/KINO-266

### Neue Features:

- [x] Create QR-Code
- [x] Save QR-Code in Datebase
- [x] Download QR-Code from Database

### Beschreibung:
Diese PR erlaubt es automatisch QR-Codes zu Buchungen zu erstellen, abzuspeichern und im nachhinein darauf zuzugreifen.
Die Zugriffsmethode muss im Nachhinein weiter entwickelt werden.

### Check:

* [x] PR geht gegen DEV und nicht MAIN!
* [ ] Funktionieren die Tests?
* [ ] Code Coverage eingehalten?
* [ ] Dokumentation?

2022-01-16 00:34 UTC, DrBackmischung requested changes

2022-01-16 00:34 UTC, DrBackmischung commented on src/main/java/de/wi2020sebgroup1/cinema/entities/Booking.java
> +	public Booking(@NotNull UUID id,@NotNull Date bookingDate, @NotNull ArrayList<Ticket> tickets, @NotNull Show show,
Was ist wenn man ne Buchung anlegt? Da bekommt man doch erst die ID

2022-01-16 16:30 UTC, Tsawlen commented on src/main/java/de/wi2020sebgroup1/cinema/entities/Booking.java
> +	public Booking(@NotNull UUID id,@NotNull Date bookingDate, @NotNull ArrayList<Ticket> tickets, @NotNull Show show,
Fürs anlegen der Buchung benutzt man eine DTO. Und der Controller generiert jetzt die ID, damit die verfügbar ist zum erstellen eines QR Codes

2022-01-17 15:39 UTC, DrBackmischung approved these changes

2022-01-19 08:28 UTC, merged